# Generated by Django 5.1.7 on 2025-03-07 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_sq', models.TextField(verbose_name='Teksti Shqip')),
                ('text_en', models.TextField(verbose_name='Teksti Anglisht')),
                ('image', models.ImageField(default=None, upload_to='gallery_images', verbose_name='Imazhi te about us')),
            ],
            options={
                'verbose_name_plural': '(4) Teksti Informues i faqes rreth nesh',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Adresa')),
                ('contact_nr', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Numri i kontaktit')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Emaili')),
                ('facebook_url', models.URLField(default='', verbose_name='Linku i facebookut')),
                ('instagram_url', models.URLField(default='', verbose_name='Linku i instagramit')),
            ],
            options={
                'verbose_name_plural': '(7) Infot rreth nesh (te kontaktit)',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Emri')),
                ('email', models.EmailField(max_length=254, verbose_name='Emaili')),
                ('subject', models.CharField(max_length=1024, verbose_name='Subjekti')),
                ('message', models.TextField(verbose_name='Mesazhi')),
            ],
            options={
                'verbose_name_plural': '(8) Mesazhet',
            },
        ),
        migrations.CreateModel(
            name='LandingPageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_sq', models.TextField(verbose_name='Teksti Shqip')),
                ('text_en', models.TextField(verbose_name='Teksti Anglisht')),
            ],
            options={
                'verbose_name_plural': '(1) Teksti informues i faqes se pare',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sq', models.CharField(max_length=512, verbose_name='Titulli Shqip')),
                ('title_en', models.CharField(max_length=512, verbose_name='Titulli Anglisht')),
                ('content_sq', models.TextField(verbose_name='Teksti Shqip')),
                ('content_en', models.TextField(verbose_name='Teksti Anglisht')),
                ('thumbnail', models.ImageField(default=None, upload_to='offer_thumbnails', verbose_name='Fotoja kryesore/thumbnail')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e krijimit')),
            ],
            options={
                'verbose_name_plural': '(6) Offertat',
            },
        ),
        migrations.CreateModel(
            name='PreviousWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sq', models.CharField(max_length=512, verbose_name='Titulli Shqip')),
                ('title_en', models.CharField(max_length=512, verbose_name='Titulli Anglisht')),
                ('content_sq', models.TextField(verbose_name='Teksti Shqip')),
                ('content_en', models.TextField(verbose_name='Teksti Anglisht')),
                ('image', models.ImageField(default=None, upload_to='work_images', verbose_name='Fotoja e punes se meparshme')),
                ('index', models.IntegerField(default=0, verbose_name='Renditja')),
            ],
            options={
                'verbose_name_plural': '(5) Punet e meparshme',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sq', models.CharField(max_length=512, verbose_name='Titulli Shqip')),
                ('title_en', models.CharField(max_length=512, verbose_name='Titulli Anglisht')),
                ('text_sq', models.TextField(verbose_name='Teksti Shqip')),
                ('text_en', models.TextField(verbose_name='Teksti Anglisht')),
                ('logo', models.TextField(choices=[('fas fa-bus', 'linja kombetare/nderkombetare'), ('bi bi-binoculars', 'guide turistike'), ('fas fa-truck', 'transport mallrash')], max_length=64)),
                ('index', models.IntegerField(default=0, verbose_name='Renditja')),
            ],
            options={
                'verbose_name_plural': '(3)  Sherbimet tona',
            },
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sq', models.CharField(max_length=512, verbose_name='Titulli Shqip')),
                ('title_en', models.CharField(max_length=512, verbose_name='Titulli Anglisht')),
                ('text_sq', models.TextField(verbose_name='Teksti Shqip')),
                ('text_en', models.TextField(verbose_name='Teksti Anglisht')),
                ('image', models.ImageField(default=None, upload_to='gallery_images', verbose_name='Fotoja')),
                ('index', models.IntegerField(default=0, verbose_name='Renditja')),
            ],
            options={
                'verbose_name_plural': '(2)  Slidet e faqes kryesore',
            },
        ),
    ]
