# Generated by Django 5.1.7 on 2025-03-08 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutustext',
            name='text_de',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Teksti Gjermanisht'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landingpagetext',
            name='text_de',
            field=models.TextField(default=1, verbose_name='Teksti Gjermanisht'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previouswork',
            name='content_de',
            field=models.TextField(default=2, verbose_name='Teksti Gjermanisht'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='previouswork',
            name='title_de',
            field=models.CharField(default=1, max_length=512, verbose_name='Titulli Gjermanisht'),
            preserve_default=False,
        ),
    ]
