# Generated by Django 5.1.7 on 2025-03-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutustext_text_de_landingpagetext_text_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_sq', models.TextField(verbose_name='Titulli Shqip')),
                ('text_en', models.TextField(verbose_name='Titulli Anglisht')),
                ('text_de', models.TextField(verbose_name='Titulli Gjermanisht')),
                ('content_sq', models.TextField(verbose_name='Permbajtja Shqip')),
                ('content_en', models.TextField(verbose_name='Permbajtja Anglisht')),
                ('content_de', models.TextField(verbose_name='Permbajtja Gjermanisht')),
            ],
            options={
                'verbose_name_plural': '(1) Teksti informues i faqes se pare',
            },
        ),
    ]
