# Generated by Django 5.1.7 on 2025-03-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_missiontext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missiontext',
            options={'verbose_name_plural': 'Mision te Index Page'},
        ),
    ]
