# Generated by Django 5.1.7 on 2025-03-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_missiontext_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiontext',
            name='text_de',
            field=models.TextField(max_length=512, verbose_name='Titulli Gjermanisht'),
        ),
        migrations.AlterField(
            model_name='missiontext',
            name='text_en',
            field=models.TextField(max_length=512, verbose_name='Titulli Anglisht'),
        ),
        migrations.AlterField(
            model_name='missiontext',
            name='text_sq',
            field=models.TextField(max_length=512, verbose_name='Titulli Shqip'),
        ),
    ]
