# Generated by Django 5.1.7 on 2025-03-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_missiontext_text_de_alter_missiontext_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontext',
            name='index',
            field=models.IntegerField(default=0, verbose_name='Renditja'),
        ),
    ]
