# Generated by Django 5.1.7 on 2025-03-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_missiontext_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missiontext',
            old_name='text_de',
            new_name='title_de',
        ),
        migrations.RenameField(
            model_name='missiontext',
            old_name='text_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='missiontext',
            old_name='text_sq',
            new_name='title_sq',
        ),
    ]
