# Generated by Django 5.1.7 on 2025-03-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_text_de_missiontext_title_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missiontext',
            name='typeLogo',
            field=models.TextField(default='', max_length=40, verbose_name='Logo Class'),
        ),
    ]
