# Generated by Django 5.1.7 on 2025-03-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_contactus_options_contactus_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, verbose_name='Renditja')),
                ('month_sq', models.TextField(max_length=512, verbose_name='Muaji Shqip')),
                ('month_en', models.TextField(max_length=512, verbose_name='Muaji Anglisht')),
                ('month_de', models.TextField(max_length=512, verbose_name='Muaji Gjermanisht')),
                ('title_sq', models.TextField(verbose_name='Titulli Shqip')),
                ('title_en', models.TextField(verbose_name='Titulli Anglisht')),
                ('title_de', models.TextField(verbose_name='Titulli Gjermanisht')),
                ('content_sq', models.TextField(verbose_name='Permbajtja Shqip')),
                ('content_en', models.TextField(verbose_name='Permbajtja Anglisht')),
                ('content_de', models.TextField(verbose_name='Permbajtja Gjermanisht')),
            ],
            options={
                'verbose_name_plural': 'Event Text te Index Page',
            },
        ),
    ]
