# Generated by Django 5.1.7 on 2025-03-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_eventtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtext',
            name='month_de',
            field=models.CharField(max_length=512, verbose_name='Muaji Gjermanisht'),
        ),
        migrations.AlterField(
            model_name='eventtext',
            name='month_en',
            field=models.CharField(max_length=512, verbose_name='Muaji Anglisht'),
        ),
        migrations.AlterField(
            model_name='eventtext',
            name='month_sq',
            field=models.CharField(max_length=512, verbose_name='Muaji Shqip'),
        ),
        migrations.AlterField(
            model_name='eventtext',
            name='title_de',
            field=models.CharField(max_length=200, verbose_name='Titulli Gjermanisht'),
        ),
        migrations.AlterField(
            model_name='eventtext',
            name='title_en',
            field=models.CharField(max_length=200, verbose_name='Titulli Anglisht'),
        ),
        migrations.AlterField(
            model_name='eventtext',
            name='title_sq',
            field=models.CharField(max_length=200, verbose_name='Titulli Shqip'),
        ),
    ]
