# Generated by Django 5.1.7 on 2025-03-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_eventtext_month_de_alter_eventtext_month_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechMissionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, verbose_name='Renditja')),
                ('typeLogo', models.TextField(default='', max_length=40, verbose_name='Logo Class')),
                ('title_sq', models.CharField(max_length=512, verbose_name='Titulli Shqip')),
                ('title_en', models.CharField(max_length=512, verbose_name='Titulli Anglisht')),
                ('title_de', models.CharField(max_length=512, verbose_name='Titulli Gjermanisht')),
                ('goal1_sq', models.CharField(max_length=512, verbose_name='Missioni 1 Shqip')),
                ('goal1_en', models.CharField(max_length=512, verbose_name='Misioni 1 Anglisht')),
                ('goal1_de', models.CharField(max_length=512, verbose_name='Misioni 1 Gjermanisht')),
                ('goal2_sq', models.CharField(max_length=512, verbose_name='Missioni 2 Shqip')),
                ('goal2_en', models.CharField(max_length=512, verbose_name='Misioni 2 Anglisht')),
                ('goal2_de', models.CharField(max_length=512, verbose_name='Misioni 2 Gjermanisht')),
                ('goal3_sq', models.CharField(max_length=512, verbose_name='Missioni 3 Shqip')),
                ('goal3_en', models.CharField(max_length=512, verbose_name='Misioni 3 Anglisht')),
                ('goal3_de', models.CharField(max_length=512, verbose_name='Misioni 3 Gjermanisht')),
                ('goal4_sq', models.CharField(max_length=512, verbose_name='Missioni 4 Shqip')),
                ('goal4_en', models.CharField(max_length=512, verbose_name='Misioni 4 Anglisht')),
                ('goal4_de', models.CharField(max_length=512, verbose_name='Misioni 4 Gjermanisht')),
                ('buttonText_sq', models.CharField(max_length=512, verbose_name='Butoni Shqip')),
                ('buttonText_en', models.CharField(max_length=512, verbose_name='Butoni Anglisht')),
                ('buttonText_de', models.CharField(max_length=512, verbose_name='Butoni Gjermanisht')),
            ],
            options={
                'verbose_name_plural': 'Event Text te Index Page',
            },
        ),
    ]
