# Generated by Django 5.1.7 on 2025-03-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_techmissiontext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techmissiontext',
            options={'verbose_name_plural': 'Tech Mission Text te Index Page'},
        ),
        migrations.AlterField(
            model_name='techmissiontext',
            name='typeLogo',
            field=models.CharField(default='', max_length=40, verbose_name='Logo Class'),
        ),
    ]
