# Generated by Django 5.1.7 on 2025-03-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_techmissiontext_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPageText',
        ),
        migrations.DeleteModel(
            name='Slides',
        ),
    ]
