# Generated by Django 5.1.7 on 2025-03-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_missiontitletext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Mesazhet nga formulari'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='device_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Pajisja'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresa'),
        ),
    ]
