# Generated by Django 5.1.7 on 2025-03-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_contactus_options_contactus_device_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Mesazhet'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='browser_info',
            field=models.TextField(blank=True, null=True, verbose_name='Browser Info'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='device_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Device Name'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
    ]
