# Generated by Django 5.1.7 on 2025-03-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_contactus_options_contactus_browser_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, verbose_name='Renditja')),
                ('name', models.CharField(max_length=255, verbose_name='Emri')),
                ('field_sq', models.CharField(max_length=255, verbose_name='Fusha Shqip')),
                ('field_en', models.CharField(max_length=255, verbose_name='Field English')),
                ('field_de', models.CharField(max_length=255, verbose_name='Feld Deutsch')),
                ('description_sq', models.TextField(verbose_name='Përshkrimi Shqip')),
                ('description_en', models.TextField(verbose_name='Description English')),
                ('description_de', models.TextField(verbose_name='Beschreibung Deutsch')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Foto')),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
