# Generated by Django 5.1.7 on 2025-03-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_teammembertitletext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previouswork',
            name='image',
            field=models.ImageField(default=None, upload_to='teamMembers', verbose_name='Fotoja e punes se meparshme'),
        ),
    ]
