# Generated by Django 5.1.7 on 2025-03-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_previouswork_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sq', models.CharField(max_length=255, verbose_name='Titulli Shqip')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title English')),
                ('title_de', models.CharField(max_length=255, verbose_name='Titel Deutsch')),
                ('subtitle_sq', models.TextField(verbose_name='Nën Titulli Shqip')),
                ('subtitle_en', models.TextField(verbose_name='Subtitle English')),
                ('subtitle_de', models.TextField(verbose_name='Untertitel Deutsch')),
                ('description_sq', models.TextField(verbose_name='Përshkrimi Shqip')),
                ('description_en', models.TextField(verbose_name='Description English')),
                ('description_de', models.TextField(verbose_name='Beschreibung Deutsch')),
                ('join_us_btn_sq', models.CharField(default='Bashkohu me ne', max_length=255, verbose_name='Butoni Bashkohu Shqip')),
                ('join_us_btn_en', models.CharField(default='Join Us', max_length=255, verbose_name='Join Us Button English')),
                ('join_us_btn_de', models.CharField(default='Mitmachen', max_length=255, verbose_name='Mitmachen Knopf Deutsch')),
                ('learn_more_btn_sq', models.CharField(default='Mëso më shumë', max_length=255, verbose_name='Butoni Mëso më Shumë Shqip')),
                ('learn_more_btn_en', models.CharField(default='Learn More', max_length=255, verbose_name='Learn More Button English')),
                ('learn_more_btn_de', models.CharField(default='Mehr Erfahren', max_length=255, verbose_name='Mehr Erfahren Knopf Deutsch')),
            ],
            options={
                'verbose_name_plural': 'Hero Section Translations',
            },
        ),
        migrations.DeleteModel(
            name='AboutUsText',
        ),
        migrations.DeleteModel(
            name='Offers',
        ),
        migrations.DeleteModel(
            name='PreviousWork',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
