# Generated by Django 5.1.7 on 2025-03-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_herosectiontext_delete_aboutustext_delete_offers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosectiontext',
            name='st_org_de',
            field=models.CharField(default='', max_length=255, verbose_name='Teksti siper titullit Deutsch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosectiontext',
            name='st_org_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Teksti siper titullit English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herosectiontext',
            name='st_org_sq',
            field=models.CharField(default=1, max_length=255, verbose_name='Teksti siper titullit Shqip'),
            preserve_default=False,
        ),
    ]
