# Generated by Django 5.1.7 on 2025-03-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_herosectiontext_st_org_de_herosectiontext_st_org_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosectiontext',
            name='start_de',
            field=models.CharField(default='', max_length=255, verbose_name='Ab'),
        ),
        migrations.AddField(
            model_name='herosectiontext',
            name='start_en',
            field=models.CharField(default='', max_length=255, verbose_name='Since'),
        ),
        migrations.AddField(
            model_name='herosectiontext',
            name='start_sq',
            field=models.CharField(default='', max_length=255, verbose_name='Qe nga'),
        ),
    ]
