# Generated by Django 5.1.7 on 2025-03-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_herosectiontext_start_de_herosectiontext_start_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sq', models.CharField(max_length=255, verbose_name='Titulli Shqip')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title English')),
                ('title_de', models.CharField(max_length=255, verbose_name='Titel Deutsch')),
                ('category_sq', models.CharField(max_length=255, verbose_name='Kategoria Shqip')),
                ('category_en', models.CharField(max_length=255, verbose_name='Category English')),
                ('category_de', models.CharField(max_length=255, verbose_name='Kategorie Deutsch')),
                ('description_sq', models.TextField(verbose_name='Përshkrimi Shqip')),
                ('description_en', models.TextField(verbose_name='Description English')),
                ('description_de', models.TextField(verbose_name='Beschreibung Deutsch')),
                ('offer_title_sq', models.CharField(max_length=255, verbose_name='Çfarë Ofrojmë Shqip')),
                ('offer_title_en', models.CharField(max_length=255, verbose_name='What We Offer English')),
                ('offer_title_de', models.CharField(max_length=255, verbose_name='Was Wir Bieten Deutsch')),
                ('offer_point1_sq', models.CharField(max_length=255, verbose_name='Pika 1 Shqip')),
                ('offer_point1_en', models.CharField(max_length=255, verbose_name='Point 1 English')),
                ('offer_point1_de', models.CharField(max_length=255, verbose_name='Punkt 1 Deutsch')),
                ('offer_point2_sq', models.CharField(max_length=255, verbose_name='Pika 2 Shqip')),
                ('offer_point2_en', models.CharField(max_length=255, verbose_name='Point 2 English')),
                ('offer_point2_de', models.CharField(max_length=255, verbose_name='Punkt 2 Deutsch')),
                ('offer_point3_sq', models.CharField(max_length=255, verbose_name='Pika 3 Shqip')),
                ('offer_point3_en', models.CharField(max_length=255, verbose_name='Point 3 English')),
                ('offer_point3_de', models.CharField(max_length=255, verbose_name='Punkt 3 Deutsch')),
                ('offer_point4_sq', models.CharField(max_length=255, verbose_name='Pika 4 Shqip')),
                ('offer_point4_en', models.CharField(max_length=255, verbose_name='Point 4 English')),
                ('offer_point4_de', models.CharField(max_length=255, verbose_name='Punkt 4 Deutsch')),
                ('button_text_sq', models.CharField(max_length=255, verbose_name='Teksti Butonit Shqip')),
                ('button_text_en', models.CharField(max_length=255, verbose_name='Button Text English')),
                ('button_text_de', models.CharField(max_length=255, verbose_name='Schaltflächen Text Deutsch')),
            ],
            options={
                'verbose_name_plural': 'About Section Translations',
            },
        ),
    ]
