# Generated by Django 5.1.7 on 2025-03-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sq', models.CharField(max_length=255, verbose_name='Titulli Shqip')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title English')),
                ('title_de', models.CharField(max_length=255, verbose_name='Titel Deutsch')),
                ('description_sq', models.TextField(verbose_name='Përshkrimi Shqip')),
                ('description_en', models.TextField(verbose_name='Description English')),
                ('description_de', models.TextField(verbose_name='Beschreibung Deutsch')),
                ('point1_sq', models.CharField(max_length=512, verbose_name='Pika 1 Shqip')),
                ('point1_en', models.CharField(max_length=512, verbose_name='Point 1 English')),
                ('point1_de', models.CharField(max_length=512, verbose_name='Punkt 1 Deutsch')),
                ('point2_sq', models.CharField(max_length=512, verbose_name='Pika 2 Shqip')),
                ('point2_en', models.CharField(max_length=512, verbose_name='Point 2 English')),
                ('point2_de', models.CharField(max_length=512, verbose_name='Punkt 2 Deutsch')),
                ('point3_sq', models.CharField(max_length=512, verbose_name='Pika 3 Shqip')),
                ('point3_en', models.CharField(max_length=512, verbose_name='Point 3 English')),
                ('point3_de', models.CharField(max_length=512, verbose_name='Punkt 3 Deutsch')),
                ('event_date_sq', models.CharField(max_length=255, verbose_name='Data Shqip')),
                ('event_date_en', models.CharField(max_length=255, verbose_name='Date English')),
                ('event_date_de', models.CharField(max_length=255, verbose_name='Datum Deutsch')),
                ('register_button_sq', models.CharField(default='Regjistrohu Tani', max_length=255, verbose_name='Butoni Shqip')),
                ('register_button_en', models.CharField(default='Pre-Register Now', max_length=255, verbose_name='Button English')),
                ('register_button_de', models.CharField(default='Jetzt Vorregistrieren', max_length=255, verbose_name='Button Deutsch')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hackathon_images/', verbose_name='Imazhi')),
            ],
            options={
                'verbose_name_plural': 'Summer Hackathon 2025 Translations',
            },
        ),
    ]
