# Generated by Django 5.1.7 on 2025-03-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_hackathontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sq', models.CharField(max_length=255, verbose_name='Titulli Shqip')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title English')),
                ('title_de', models.CharField(max_length=255, verbose_name='Titel Deutsch')),
                ('subtitle_sq', models.TextField(verbose_name='Nëntitulli Shqip')),
                ('subtitle_en', models.TextField(verbose_name='Subtitle English')),
                ('subtitle_de', models.TextField(verbose_name='Untertitel Deutsch')),
                ('connect_sq', models.CharField(max_length=255, verbose_name='Lidhu me Ne Shqip')),
                ('connect_en', models.CharField(max_length=255, verbose_name='Connect With Us English')),
                ('connect_de', models.CharField(max_length=255, verbose_name='Verbinde Dich mit Uns Deutsch')),
                ('description_sq', models.TextField(verbose_name='Përshkrimi Shqip')),
                ('description_en', models.TextField(verbose_name='Description English')),
                ('description_de', models.TextField(verbose_name='Beschreibung Deutsch')),
                ('email_label_sq', models.CharField(default='Email:', max_length=255, verbose_name='Email Label Shqip')),
                ('email_label_en', models.CharField(default='Email:', max_length=255, verbose_name='Email Label English')),
                ('email_label_de', models.CharField(default='E-Mail:', max_length=255, verbose_name='Email Label Deutsch')),
                ('address_label_sq', models.CharField(default='Adresa Kryesore:', max_length=255, verbose_name='Adresa Shqip')),
                ('address_label_en', models.CharField(default='Main Address:', max_length=255, verbose_name='Address English')),
                ('address_label_de', models.CharField(default='Hauptadresse:', max_length=255, verbose_name='Adresse Deutsch')),
                ('form_name_sq', models.CharField(default='Emri Juaj', max_length=255, verbose_name='Emri Shqip')),
                ('form_name_en', models.CharField(default='Your Name', max_length=255, verbose_name='Name English')),
                ('form_name_de', models.CharField(default='Ihr Name', max_length=255, verbose_name='Name Deutsch')),
                ('form_email_sq', models.CharField(default='Emaili Juaj', max_length=255, verbose_name='Email Shqip')),
                ('form_email_en', models.CharField(default='Your Email', max_length=255, verbose_name='Email English')),
                ('form_email_de', models.CharField(default='Ihre E-Mail', max_length=255, verbose_name='Email Deutsch')),
                ('form_subject_sq', models.CharField(default='Subjekti', max_length=255, verbose_name='Subjekti Shqip')),
                ('form_subject_en', models.CharField(default='Subject', max_length=255, verbose_name='Subject English')),
                ('form_subject_de', models.CharField(default='Betreff', max_length=255, verbose_name='Betreff Deutsch')),
                ('form_message_sq', models.CharField(default='Mesazhi Juaj', max_length=255, verbose_name='Mesazhi Shqip')),
                ('form_message_en', models.CharField(default='Your Message', max_length=255, verbose_name='Message English')),
                ('form_message_de', models.CharField(default='Ihre Nachricht', max_length=255, verbose_name='Nachricht Deutsch')),
                ('submit_button_sq', models.CharField(default='Dërgo Mesazh', max_length=255, verbose_name='Butoni Shqip')),
                ('submit_button_en', models.CharField(default='Send Message', max_length=255, verbose_name='Button English')),
                ('submit_button_de', models.CharField(default='Nachricht Senden', max_length=255, verbose_name='Button Deutsch')),
                ('success_message_sq', models.CharField(default='Mesazhi juaj është dërguar. Faleminderit!', max_length=255, verbose_name='Mesazhi i Suksesit Shqip')),
                ('success_message_en', models.CharField(default='Your message has been sent. Thank you!', max_length=255, verbose_name='Success Message English')),
                ('success_message_de', models.CharField(default='Ihre Nachricht wurde gesendet. Danke!', max_length=255, verbose_name='Erfolgsmeldung Deutsch')),
            ],
            options={
                'verbose_name_plural': 'Contact Section Translations',
            },
        ),
    ]
