# Generated by Django 5.1.7 on 2025-03-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_contacttext'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename_sq', models.CharField(max_length=255, verbose_name='Emri i shoqatës')),
                ('sitename_en', models.CharField(max_length=255, verbose_name='Society Name')),
                ('sitename_de', models.CharField(max_length=255, verbose_name='Name der Gesellschaft')),
                ('description_sq', models.TextField(verbose_name='Përshkrimi Shqip')),
                ('description_en', models.TextField(verbose_name='Description English')),
                ('description_de', models.TextField(verbose_name='Beschreibung Deutsch')),
                ('copyright_sq', models.CharField(max_length=255, verbose_name='E drejta e autorit Shqip')),
                ('copyright_en', models.CharField(max_length=255, verbose_name='Copyright English')),
                ('copyright_de', models.CharField(max_length=255, verbose_name='Urheberrecht Deutsch')),
            ],
            options={
                'verbose_name_plural': 'Footer Translations',
            },
        ),
    ]
