# Generated by Django 5.1.7 on 2025-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_eventtitletext'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechTitleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sq', models.CharField(max_length=200, verbose_name='Titulli Shqip')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titulli Anglisht')),
                ('title_de', models.CharField(max_length=200, verbose_name='Titulli Gjermanisht')),
                ('subtitle_sq', models.CharField(max_length=200, verbose_name='Nen Titulli Shqip')),
                ('subtitle_en', models.CharField(max_length=200, verbose_name='Nen Titulli Anglisht')),
                ('subtitle_de', models.CharField(max_length=200, verbose_name='Nen Titulli Gjermanisht')),
            ],
        ),
    ]
