# Generated by Django 5.1.7 on 2025-03-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_herosectiontext_name_sq'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosectiontext',
            name='name_de',
            field=models.CharField(default='', max_length=255, verbose_name='Name of Association Deutsch'),
        ),
        migrations.AddField(
            model_name='herosectiontext',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='Name of Association English'),
        ),
        migrations.AlterField(
            model_name='herosectiontext',
            name='name_sq',
            field=models.CharField(default='', max_length=255, verbose_name='Name of Association Shqip'),
        ),
    ]
