# Generated by Django 5.1.7 on 2025-06-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_herosectiontext_name_de_herosectiontext_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('month', models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')], verbose_name='Month')),
                ('day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], verbose_name='Day')),
                ('title_sq', models.CharField(max_length=200, verbose_name='Titulli Shqip')),
                ('title_en', models.CharField(max_length=200, verbose_name='Titulli Anglisht')),
                ('title_de', models.CharField(max_length=200, verbose_name='Titulli Gjermanisht')),
                ('content_sq', models.TextField(verbose_name='Permbajtja Shqip')),
                ('content_en', models.TextField(verbose_name='Permbajtja Anglisht')),
                ('content_de', models.TextField(verbose_name='Permbajtja Gjermanisht')),
            ],
            options={
                'ordering': ['year', 'month', 'day'],
            },
        ),
        migrations.DeleteModel(
            name='EventText',
        ),
    ]
