# Generated by Django 5.1.7 on 2025-06-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_upcomingevents_delete_eventtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevents',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
    ]
