# Generated by Django 5.1.7 on 2025-09-02 19:21

from django.db import migrations
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_upcomingevents_active'),
    ]

    operations = [
        # This migration syncs with the production database schema
        # The production database already has the correct fields:
        # - TeamMember.profile_image_url (already exists)
        # - HackathonText.image (needs type update to ImageURLField)
        
        # Update HackathonText.image field to use our custom ImageURLField
        migrations.AlterField(
            model_name='hackathontext',
            name='image',
            field=main.models.ImageURLField(blank=True, max_length=500, null=True, verbose_name='Imazhi URL'),
        ),
    ]
