# Generated by Django 5.1.7 on 2025-09-02 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_sync_with_production_schema'),
    ]

    operations = [
        # Remove unused name fields from HeroSectionText
        migrations.RemoveField(
            model_name='herosectiontext',
            name='name_sq',
        ),
        migrations.RemoveField(
            model_name='herosectiontext',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='herosectiontext',
            name='name_de',
        ),
        # Remove unused ContactInfo model entirely
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
