# Generated by Django 5.1.7 on 2025-09-02 19:34

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_redundant_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_per_page', models.IntegerField(default=6, help_text='Number of Instagram posts to display on the homepage', verbose_name='Posts Per Page')),
                ('show_captions', models.BooleanField(default=True, help_text='Whether to display post captions', verbose_name='Show Captions')),
                ('max_caption_length', models.IntegerField(default=150, help_text='Maximum number of characters to show in captions (0 for no limit)', verbose_name='Max Caption Length')),
                ('section_title_sq', models.CharField(default='Postimet tona në Instagram', max_length=255, verbose_name='Section Title (Albanian)')),
                ('section_title_en', models.CharField(default='Our Instagram Posts', max_length=255, verbose_name='Section Title (English)')),
                ('section_title_de', models.CharField(default='Unsere Instagram-Posts', max_length=255, verbose_name='Section Title (German)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to show the Instagram section on the website', verbose_name='Enable Instagram Section')),
            ],
            options={
                'verbose_name': 'Instagram Configuration',
                'verbose_name_plural': 'Instagram Configuration',
            },
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, help_text='Instagram post caption', verbose_name='Caption')),
                ('media_url', main.models.ImageURLField(help_text='Direct URL to the Instagram media (image/video)', max_length=500, verbose_name='Media URL')),
                ('post_url', models.URLField(help_text='Link to the original Instagram post', verbose_name='Post URL')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which posts should be displayed (lower numbers first)', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this post should be displayed on the website', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Instagram Post',
                'verbose_name_plural': 'Instagram Posts',
                'ordering': ['display_order', '-created_at'],
            },
        ),

    ]
