# Generated by Django 5.1.7 on 2025-09-02 19:47

import main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_add_instagram_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='image',
        ),
        migrations.AddField(
            model_name='teammember',
            name='profile_image_url',
            field=main.models.ImageURLField(default='https://via.placeholder.com/300x300?text=Team+Member', max_length=500, verbose_name='Foto URL'),
        ),
    ]
