# Generated by Django 5.1.7 on 2025-09-02 20:03

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_teammember_image_teammember_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampost',
            name='media_url',
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='media_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of all media URLs for carousel posts (JSON format)', verbose_name='Media URLs'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='post_type',
            field=models.CharField(choices=[('image', 'Single Image'), ('carousel', 'Multiple Images'), ('video', 'Video'), ('reel', 'Reel')], default='image', help_text='Type of Instagram post', max_length=20, verbose_name='Post Type'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='primary_media_url',
            field=main.models.ImageURLField(blank=True, help_text='URL to the main/first image or video thumbnail', max_length=500, verbose_name='Primary Media URL'),
        ),
    ]
