# Generated by Django 5.1.7 on 2025-09-03 10:06

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_update_instagram_multiple_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathontext',
            name='image',
            field=main.models.ImageURLField(blank=True, max_length=2000, null=True, verbose_name='Imazhi URL'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='primary_media_url',
            field=models.URLField(blank=True, help_text='URL to the main/first image or video thumbnail', max_length=2000, verbose_name='Primary Media URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='profile_image_url',
            field=main.models.ImageURLField(default='https://via.placeholder.com/300x300?text=Team+Member', max_length=2000, verbose_name='Foto URL'),
        ),
    ]
