# Generated by Django 5.1.7 on 2025-09-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_increase_url_field_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramconfig',
            name='max_caption_length',
            field=models.IntegerField(default=2000, help_text='Maximum number of characters to show in captions (0 for no limit)', verbose_name='Max Caption Length'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='post_url',
            field=models.URLField(help_text='Link to the original Instagram post', unique=True, verbose_name='Post URL'),
        ),
    ]
