name: Deploy Site
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *'  # Runs hourly

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repo (without submodules)
      uses: actions/checkout@v4
      with:
        submodules: false  # Don't fetch submodules yet

    - name: Set up SSH Key for accessing private submodule
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.WEBSITE_CONTENT_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Update submodules (pull private repo)
      run: |
        git submodule update --init --recursive

    - name: Build Site
      run: |
        bundle install
        bundle exec jekyll build

    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
